stages:
  - build
  - test
  - deploy
  - cleanup

variables:
  WEBDEV_PATH: /var/www/vhosts/webdev/knowledgehub
  STAGING_PATH: /var/www/vhosts/knowledgehub
  PROD_PATH: /var/www/vhosts/ebiz

cache:
  paths:
    - vendor/
    - node_modules/

include:
  - local: /.gitlab-ci/prod.yml
    rules:
      - if: $CI_COMMIT_BRANCH == "main"
  - local: /.gitlab-ci/staging.yml
    rules:
      - if: $CI_COMMIT_BRANCH == "staging"
